### ISSUE TITLE
Docker running problems

### ISSUE THREAD

**Issue by lemonviv** [cloud-security-research/sgx-ra-tls#27]
Hi, 

I use docker ubuntu 16.04 to run the project with `SPID`, `EPID_SUBSCRIPTION_KEY`, `QUOTE_TYPE` correctly set up. The `docker build` command receives the following warnings when installing `libsgx_enclave_common` but no errors.

```
Optional modules libiclsclient.so or iclsInit() cannot be found.
Trusted platform service is unavailable. Refer to README for details.
```
Then I run the docker image and first build with `sgxsdk`, it was correct but when I ran the example `./App -s` I received `Failed to create Enclave : error 8198 - 0x2006.`

The other problem is when building with `graphene`, I received the following error.

```
Traceback (most recent call last):
  File "deps/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token", line 157, in <module>
    sys.exit(main())
  File "deps/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token", line 151, in main
    token = connect_aesmd(attr)
  File "deps/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token", line 117, in connect_aesmd
    raise Exception("Failed. (Error Code = %d)" % (ret_msg.ret.error))
Exception: Failed. (Error Code = 30)
Makefile:169: recipe for target 'wolfssl-ssl-server' failed
make: *** [wolfssl-ssl-server] Error 1
rm ias-ra-wolfssl.c
+ exit 1
```

It seems that both problems are related to `aesmd` service. I checked this service in the host os and it is running normally. I wonder if there is anything I missed here. Any advice would be highly appreciated.

Thanks and best regards,
Yuncheng

**Comment by lemonviv** [comment]
Might be some problems in sdk or psw, I re-install the sdk, psw, and driver in host os, and it could work now.
